"""data_types CUDA->MUSA porting rules."""

MAPPING = {
    '__nv_bfloat16': '__mt_bfloat16',
    '__nv_bfloat162': '__mt_bfloat162',
    '__nv_half': '__half',
    'nv_bfloat16': '__mt_bfloat16',
    'nv_bfloat162': '__mt_bfloat162',
    'nv_half': '__half',
    '__NV_E4M3': '__MT_E4M3',
    '__NV_E5M2': '__MT_E5M2',
    '__NV_SATFINITE': '__MT_SATFINITE',
    '__nv_fp8_e4m3': '__mt_fp8_e4m3',
    '__nv_fp8_e5m2': '__mt_fp8_e5m2',
    '__nv_fp8_interpretation_t': '__mt_fp8_interpretation_t',
    '__nv_fp8_storage_t': '__mt_fp8_storage_t',
    '__nv_fp8x2_e4m3': '__mt_fp8x2_e4m3',
    '__nv_fp8x2_e5m2': '__mt_fp8x2_e5m2',
    '__nv_fp8x2_storage_t': '__mt_fp8x2_storage_t',
    '__nv_fp8x4_e4m3': '__mt_fp8x4_e4m3',
    '__nv_fp8x4_e5m2': '__mt_fp8x4_e5m2',
    '__nv_fp8x4_storage_t': '__mt_fp8x4_storage_t',
    '__nv_cvt_bfloat16raw_to_fp8': '__musa_cvt_bfloat16raw_to_fp8',
    '__nv_cvt_float2_to_fp8x2': '__musa_cvt_float2_to_fp8x2',
    '__nv_cvt_float_to_fp8': '__musa_cvt_float_to_fp8',
    '__nv_cvt_fp8_to_halfraw': '__musa_cvt_fp8_to_halfraw',
    '__nv_cvt_fp8x2_to_halfraw2': '__musa_cvt_fp8x2_to_halfraw2',
    '#include <cuda_fp8.h>': '#include <musa_fp8.h>',
    'CUDA_R_8F_E4M3': 'MUSA_R_8F_E4M3',
    'CUDA_R_8F_E5M2': 'MUSA_R_8F_E5M2',
    'cuda_fp16.h': 'musa_fp16.h',
    'cuda_bf16.h': 'musa_bf16.h',
    # torch_musa's torch::headeronly snapshot omits these scalar-type headers;
    # the c10 variants carry the same definitions. Only the dtype headers move
    # (Exception.h / ScalarType.h under torch/headeronly resolve on torch_musa).
    '#include <torch/headeronly/util/Float8_e4m3fn.h>': '#include <c10/util/Float8_e4m3fn.h>',
    '#include <torch/headeronly/util/Float8_e4m3fnuz.h>': '#include <c10/util/Float8_e4m3fnuz.h>',
    '#include <torch/headeronly/util/BFloat16.h>': '#include <c10/util/BFloat16.h>',
    '#include <torch/headeronly/util/Half.h>': '#include <c10/util/Half.h>',
}
